---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: antrea-crs
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cni: antrea
  resources:
  - kind: ConfigMap
    name: antrea-crs-cm
---
