---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: csi-crs
spec:
  clusterSelector:
    matchLabels:
      csi: csi-crs 
  resources:
  - kind: ConfigMap
    name: csi-controller-crs-cm
  - kind: ConfigMap
    name: csi-node-crs-cm
  - kind: ConfigMap
    name: csi-driver-crs-cm
---
