---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: kube-system
data:
  vcloud-csi-config.yaml: |+
    vcd:
      host: ${VCD_SITE}
      org: ${VCD_ORGANIZATION}
      vdc: ${VCD_ORGANIZATION_VDC}
      vAppName: ${VCD_VAPP_NAME}
    clusterid: ${VCD_CLUSTERID}
immutable: true
---
