---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: kube-system
data:
  vcloud-csi-config.yaml: |+
    vcd:
      host: __SITE__
      org: __ORG__
      vdc: __OVDC__
      vAppName: __VAPPNAME__
    clusterid: __CLUSTERID__
immutable: true
---
